[default]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.10"
verbosity = 4
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
]