[hardhat]
src = 'src/contracts'
out = 'out'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
]